# Generated by Django 3.0.4 on 2020-04-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssesRecord',
            new_name='AccessRecord',
        ),
    ]
